[pytest]
# Tells Django which settings file to load before any test is imported.
DJANGO_SETTINGS_MODULE = config.settings.development

# Adds the project root to Python's import path,
pythonpath = .

# Which files pytest treats as tests.
python_files = test_*.py *_tests.py
